import { write, json } from './io.mjs';
import { format } from 'prettier';
const esc = (v) =>
  String(v ?? 'NOT PINNED')
    .replaceAll('|', '\\|')
    .replaceAll('\n', ' ');
const table = (head, rows) =>
  `| ${head.join(' | ')} |\n| ${head.map(() => '---').join(' | ')} |\n${rows.map((row) => `| ${row.map(esc).join(' | ')} |`).join('\n')}\n`;
export function render(report) {
  const out = {};
  const shell = report.subsystems.find((s) => s.id === 'SHELL');
  out['shell-compatibility.md'] =
    '# Shell compatibility — Bash 5.2.37 subset\n\nGenerated by the Milestone 0 pipeline. Readiness describes each tested capability, not complete GNU Bash compatibility.\n\n' +
    table(
      ['Capability', 'State', 'Required case IDs', 'Remaining limits'],
      (shell?.capabilities ?? []).map((c) => [
        c.id,
        c.effectiveState,
        c.requiredTests.join(', '),
        c.limitations.join('; '),
      ]),
    ) +
    '\n## Foundation\n\n' +
    (shell?.effectiveState ?? 'MISSING') +
    ': ' +
    (shell?.reason ?? '') +
    '\n\n' +
    'See [architecture](../shell/architecture.md), [supported subset](../shell/bash-5.2-subset.md) and [milestone report](../shell/MILESTONE-1A.md). Performance measurements: `artifacts/shell-performance.json`.\n\n' +
    table(
      ['Case', 'Result', 'Reason'],
      report.verification.caseResults
        .filter((c) => c.id.startsWith('shell/'))
        .map((c) => [c.id, c.result, c.reason ?? '']),
    ) +
    '\n## Coreutils blockers\n\n' +
    (report.queue.software.find((s) => s.id === 'coreutils')?.blockedBy.join(', ') ||
      'None reported by dependency graph') +
    '\n\n## Performance\n\n' +
    (report.shellPerformance
      ? report.shellPerformance.profile +
        '\n\n' +
        table(
          ['Measurement', 'Mean ms / value'],
          [
            ['Simple parse', report.shellPerformance.simpleParse.meanMs.toFixed(3)],
            [
              'Moderate script parse',
              report.shellPerformance.moderateParse.measurement.meanMs.toFixed(3),
            ],
            [
              'Three-stage, 100000 lines',
              report.shellPerformance.threeStage100000Lines.meanMs.toFixed(3),
            ],
            ['Peak pipe bytes', report.shellPerformance.observedPeakPipeBytes],
            ['Pipe capacity bytes', report.shellPerformance.pipeCapacityBytes],
            ...report.shellPerformance.glob.map((sample) => [
              `Glob ${sample.actualEntries} entries (${sample.requestedEntries} requested)`,
              sample.execution.meanMs.toFixed(3),
            ]),
          ],
        )
      : 'No current performance capture; run cli:compat.\n');
  out['cli-dashboard.md'] =
    '# CYBER WAR — CLI Compatibility\n\nGenerated from runtime registrations and current evidence. PARTIAL is not certification.\n\n' +
    table(
      ['Metric', 'Value'],
      Object.entries(report.summary).map(([k, v]) => [
        k,
        typeof v === 'object' ? JSON.stringify(v) : v,
      ]),
    ) +
    '\n## Subsystem readiness\n\n' +
    table(
      ['Subsystem', 'State', 'Reason'],
      report.subsystems.map((s) => [s.id, s.effectiveState, s.reason]),
    ) +
    '\n## Next work\n\n' +
    JSON.stringify(report.queue.next, null, 2) +
    '\n';
  out['cli-inventory.md'] =
    '# CLI inventory v2\n\nNames include catalog dispatch names; aliases and GUI launchers are separate from executable progress.\n\n' +
    table(
      ['Name', 'Software', 'Kind', 'Version', 'Status', 'Implementation'],
      report.commands.map((c) => [
        c.command,
        c.softwareId,
        c.implementationKind,
        c.referenceVersion,
        c.effectiveStatus,
        c.implementation,
      ]),
    );
  out['cli-software-families.md'] =
    '# Software families\n\n' +
    report.software
      .map(
        (s) =>
          `## ${s.id}\n\n${s.effectiveStatus}; ${s.classification}; package: ${s.packageName}; reference: ${s.referenceVersion ?? 'NOT PINNED'}.\n\nExecutables: ${
            report.commands
              .filter((c) => s.executables.includes(c.id))
              .map((c) => '`' + c.command + '`')
              .join(', ') || 'None (launcher only)'
          }.\n\nAliases: ${
            report.commands
              .filter((c) => s.aliases.includes(c.id))
              .map((c) => '`' + c.command + '` → `' + c.aliasOf + '`')
              .join(', ') || 'None'
          }.\n`,
      )
      .join('\n');
  out['unpinned-software.md'] =
    '# Unpinned REAL_COMPAT software\n\n' +
    table(
      ['Software', 'Package'],
      report.software
        .filter((s) => s.classification === 'REAL_COMPAT' && !s.referenceVersion)
        .map((s) => [s.id, s.packageName]),
    );
  out['catalog-only-software.md'] =
    '# Catalog-only software\n\nThese names invoke an inspection adapter, not the native software CLI.\n\n' +
    table(
      ['Software', 'Catalog-only executables'],
      report.software
        .map((s) => [
          s.id,
          report.commands
            .filter((c) => c.softwareId === s.id && c.implementationKind === 'CATALOG_ONLY')
            .map((c) => c.command)
            .join(', '),
        ])
        .filter((r) => r[1]),
    );
  for (const [filename, status] of [
    ['partial-cli.md', 'PARTIAL'],
    ['verified-cli.md', 'VERIFIED'],
  ])
    out[filename] =
      `# ${status} CLI\n\n` +
      table(
        ['Command', 'Software', 'Missing gates', 'Blocked by'],
        report.commands
          .filter((c) => c.effectiveStatus === status)
          .map((c) => [c.command, c.softwareId, c.missingGates.join(', '), c.blockedBy.join(', ')]),
      );
  out['cli-next-work.md'] =
    '# CLI implementation queue\n\nOrder: wave, priority, dependency readiness, reference readiness, mission use, software ID. Blocked entries require foundation work first.\n\n' +
    table(
      ['Software', 'Wave', 'Priority', 'Action', 'Blockers'],
      report.queue.software.map((s) => [
        s.id,
        s.wave,
        s.priority,
        s.queueState,
        s.blockedBy.join(', '),
      ]),
    );
  out['cli-legacy-results.md'] =
    '# Legacy result adapters\n\nThese handlers still return GameResult<String>. Dispatch wraps them in the existing structured CommandResult; stream/error fidelity still needs migration.\n\n' +
    table(
      ['Command', 'Handler'],
      report.commands
        .filter((c) => c.resultContract === 'LEGACY_STRING')
        .map((c) => [c.command, c.implementation]),
    );
  out['cli-verification.md'] =
    '# Verification evidence\n\nCurrent fingerprint: ' +
    (report.verification.evidenceFingerprint ??
      'No current execution evidence; run pnpm cli:compat') +
    '\n\n' +
    table(
      ['Test', 'Result', 'Reason'],
      report.verification.caseResults.map((c) => [c.id, c.result, c.reason]),
    ) +
    '\nHost guard: ' +
    report.verification.hostIsolation.result +
    '\n\n' +
    report.verification.errors.map((e) => '- ' + e).join('\n') +
    '\n';
  return out;
}
export async function generate(report) {
  const formatting = json('.prettierrc.json');
  write('artifacts/cli-inventory.json', report);
  write('artifacts/cli-implementation-queue.json', report.queue);
  write('artifacts/cli-verification.json', report.verification);
  for (const [name, text] of Object.entries(render(report)))
    write(`docs/generated/${name}`, await format(text, { ...formatting, parser: 'markdown' }));
  const compact = {
    schemaVersion: 2,
    commandCount: report.summary.commandNames,
    summary: report.summary,
    commands: report.commands.map((c) => ({
      command: c.command,
      id: c.id,
      softwareId: c.softwareId,
      sources: c.sources,
      implementationKind: c.implementationKind,
      effectiveStatus: c.effectiveStatus,
    })),
  };
  write(
    'docs/cli/inventory.json',
    await format(JSON.stringify(compact), { ...formatting, parser: 'json' }),
  );
  write(
    'docs/cli/inventory.md',
    '# CLI inventory\n\nThe canonical report is now [CLI inventory v2](../generated/cli-inventory.md), with [dashboard](../generated/cli-dashboard.md) and [workflow](../cli-compatibility/README.md).\n',
  );
}
