import test from'node:test';
import assert from'node:assert/strict';
import{GameWorld,LEVELS,WEAPONS}from'../dist/engine.js';
import{defaultProfile,purchase,equip,normalizeProfile}from'../dist/store.js';
import{CHARACTERS,selectCharacter,getCharacter}from'../dist/characters.js';
import{AudioSystem}from'../dist/audio.js';
import{Renderer,CHARACTER_FRAMES}from'../dist/render.js';
const tick=(world,count,input={})=>{for(let i=0;i<count;i++)world.update(1/60,typeof input==='function'?input(i):input);};

test('Three distinct stages have checkpoints, reachable extraction and secrets',()=>{assert.equal(LEVELS.length,3);for(const l of LEVELS){assert.ok(l.length>=4000);assert.ok(l.platforms.length>=10);assert.ok(l.secrets.length>=2);assert.equal(l.ground.at(-1)[1],l.length);for(const cp of l.checkpoints)assert.ok(l.ground.some(([a,b])=>cp>=a&&cp<b));}});
test('Movement, landing, double jump and dash obey grounded physics',()=>{const w=new GameWorld();tick(w,30);assert.ok(w.player.onGround);const start=w.player.x;tick(w,45,{right:true});assert.ok(w.player.x>start+140);w.update(1/60,{jump:true});const vy=w.player.vy;assert.ok(vy<0);tick(w,12);w.update(1/60,{jump:true});assert.equal(w.player.jumps,2);tick(w,4);w.update(1/60,{jump:true});assert.equal(w.player.jumps,2);w.update(1/60,{dash:true});assert.ok(w.player.dashTime>0);assert.ok(w.player.dashCd>0);});
test('Bullets damage hostiles; each hostile awards one kill',()=>{const w=new GameWorld();w.enemies=[];w.crates=[];const e={id:99,x:145,y:405,w:28,h:46,hp:32,maxHp:32,alive:true,type:'turret',shootCd:100,anim:0,vy:0,phase:0};w.enemies.push(e);tick(w,100,{shoot:true,autoAim:true});assert.equal(e.alive,false);assert.equal(w.kills,1);assert.equal(w.takeEvents().filter(e=>e.type==='kill').length,1);});
test('Shots spawn at the weapon muzzle in either direction',()=>{const w=new GameWorld();w.enemies=[];w.player.aim=0;w.player.shotCd=0;w.shoot({autoAim:false});const right=w.bullets[0],rightMuzzle=w.muzzlePoint(0);assert.equal(right.x,rightMuzzle.x);assert.equal(right.y,rightMuzzle.y);w.bullets=[];w.player.ammo=WEAPONS[0].mag;w.player.shotCd=0;w.player.aim=Math.PI;w.shoot({autoAim:false});const left=w.bullets[0],leftMuzzle=w.muzzlePoint(Math.PI);assert.equal(left.x,leftMuzzle.x);assert.equal(left.y,leftMuzzle.y);assert.ok(left.x<right.x);});
test('Reload prevents shots then restores the selected magazine',()=>{const w=new GameWorld();tick(w,8);w.player.ammo=0;w.shoot({autoAim:true});assert.ok(w.player.reloading>0);assert.equal(w.bullets.length,0);tick(w,80);assert.equal(w.player.ammo,WEAPONS[0].mag);assert.equal(w.player.reloading,0);});
test('Protection frames stop stacked hits; fatal damage ends the run once',()=>{const w=new GameWorld();w.player.invuln=0;assert.equal(w.damagePlayer(20,0),true);assert.equal(w.damagePlayer(20,0),false);assert.equal(w.player.hp,80);w.player.invuln=0;w.damagePlayer(100,0);assert.equal(w.status,'dead');const time=w.time;tick(w,30,{right:true});assert.equal(w.time,time);assert.equal(w.takeEvents().filter(e=>e.type==='dead').length,1);});
test('Pulse damages nearby enemies and clears nearby hostile projectiles',()=>{const w=new GameWorld();const e=w.enemies[0];e.x=160;e.y=414;e.hp=100;e.alive=true;w.enemyBullets=[{x:115,y:420,vx:0,vy:0,life:3,r:3,damage:10}];w.update(1/60,{pulse:true});assert.equal(e.hp,30);assert.equal(w.enemyBullets.length,0);assert.ok(w.player.pulseCd>6);});
test('A collected secret rewards once per operation',()=>{const w=new GameWorld();w.enemies=[];const s=w.level.secrets[0];w.player.x=s.x-12;w.player.y=s.y-20;w.player.vy=0;tick(w,5);assert.equal(w.takeEvents().filter(e=>e.type==='secret').length,1);assert.equal(w.secretsFound.length,1);});
test('Shop charges once and equips only owned matching items',()=>{const p=defaultProfile();assert.ok(purchase(p,'visor').ok);assert.equal(p.credits,140);assert.equal(p.loadout.accessory,'visor');assert.equal(purchase(p,'visor').ok,false);assert.equal(purchase(p,'railgun').ok,false);assert.equal(p.credits,140);assert.equal(equip(p,'drone'),false);assert.equal(equip(p,'ivory'),true);});
test('Saved profiles reject invalid items, slots and balances',()=>{const p=normalizeProfile({credits:-20,owned:['invented','shield','carbine'],loadout:{weapon:'shield',equipment:'shield'},settings:{volume:5}});assert.equal(p.credits,0);assert.equal(p.loadout.weapon,'carbine');assert.equal(p.loadout.equipment,'shield');assert.equal(p.settings.volume,1);assert.ok(!p.owned.includes('invented'));});
test('Purchased equipment changes real combat values and healing',()=>{const p=defaultProfile();p.owned.push('shield','visor','medkit','railgun');p.loadout.equipment='shield';p.loadout.accessory='visor';p.loadout.weapon='railgun';const w=new GameWorld(0,{profile:p});assert.equal(w.player.maxHp,130);assert.equal(w.player.weapon,3);assert.equal(w.damageMult,1.18);p.loadout.equipment='medkit';w.applyLoadout(p);w.player.hp=40;w.pickups=[{x:w.player.x,y:w.player.y,w:18,h:24,alive:true}];w.update(1/60);assert.equal(w.player.hp,68);});
test('All bosses change phases and extraction only opens after defeat',()=>{for(let i=0;i<3;i++){const w=new GameWorld(i);w.enemies=[];w.player.x=w.level.length-750;w.update(1/60);assert.ok(w.boss?.alive);assert.equal(w.boss.phase,1);w.boss.hp=w.boss.maxHp*.25;w.update(1/60);assert.equal(w.boss.phase,3);w.damageEnemy(w.boss,9999);assert.ok(w.bossDefeated);w.player.x=w.level.length-90;w.update(1/60);assert.equal(w.status,'clear');assert.equal(w.takeEvents().filter(e=>e.type==='clear').length,1);}});
test('Each level supports complete traversal using movement and repeated jumps',()=>{for(let i=0;i<3;i++){const w=new GameWorld(i);w.enemies=[];w.crates=[];w.bossStarted=true;w.bossDefeated=true;w.level={...w.level,hazards:[]};let highX=0;for(let f=0;f<12000&&w.status==='playing';f++){w.player.invuln=10;w.update(1/60,{right:true,jump:f%24===0,dash:f%150===0});highX=Math.max(highX,w.player.x);}assert.equal(w.status,'clear',`Stage ${i+1} stopped at ${Math.round(w.player.x)} (max ${Math.round(highX)})`);}});


test('Four free characters alternate men and women and persist without changing equipment',()=>{assert.deepEqual(CHARACTERS.map(c=>c.gender),['HOMEM','MULHER','HOMEM','MULHER']);const p=defaultProfile();purchase(p,'ember');const owned=[...p.owned],credits=p.credits;for(const c of CHARACTERS){assert.ok(selectCharacter(p,c.id));assert.equal(normalizeProfile(JSON.parse(JSON.stringify(p))).character,c.id);assert.deepEqual(p.owned,owned);assert.equal(p.credits,credits);const w=new GameWorld(0,{profile:p});assert.equal(w.profile.character,c.id);assert.equal(w.profile.loadout.outfit,'ember');assert.equal(w.player.maxHp,100);}assert.equal(selectCharacter(p,'unknown'),false);assert.equal(p.character,'nika');assert.equal(normalizeProfile({character:'unknown'}).character,'kaia');assert.equal(getCharacter().id,'kaia');});
test('All characters render every authored pose and preserve outfit variants',()=>{const calls=[],image={},tinted={};const renderer={agentImage(_id,outfit){return outfit==='ember'?tinted:image}};const context={save(){},restore(){},translate(){},scale(){},drawImage(...args){calls.push(args)}};for(const c of CHARACTERS){assert.equal(CHARACTER_FRAMES[c.id].length,14);for(let frame=0;frame<14;frame++){Renderer.prototype.drawAgent.call(renderer,context,c.id,'ivory',frame,0,0,55,67);assert.equal(calls.at(-1)[0],image);assert.deepEqual(calls.at(-1).slice(1,5),CHARACTER_FRAMES[c.id][frame]);assert.ok(calls.at(-1).at(-1)>0);}Renderer.prototype.drawAgent.call(renderer,context,c.id,'ember',7,0,0,55,67);assert.equal(calls.at(-1)[0],tinted);}});


test('Music and effects have independent persisted volumes with a master mute',()=>{const audio=new AudioSystem();audio.ctx={currentTime:1};const gain=()=>({gain:{value:0,setTargetAtTime(v){this.value=v;}}});audio.master=gain();audio.musicBus=gain();audio.effectsBus=gain();audio.setEnabled(true);audio.setVolume(.7);audio.setMusicVolume(.3);audio.setEffectsVolume(.9);assert.equal(audio.musicBus.gain.value,.3);assert.equal(audio.effectsBus.gain.value,.9);audio.setScene('pause');assert.equal(audio.musicBus.gain.value,.3*.28);assert.equal(audio.effectsBus.gain.value,.9);audio.setEnabled(false);assert.equal(audio.master.gain.value,0);const p=normalizeProfile({settings:{music:2,effects:-1}});assert.equal(p.settings.music,1);assert.equal(p.settings.effects,0);assert.equal(normalizeProfile({}).settings.music,.65);});
test('Background music schedules through its own bus and recovers after an inactive tab',()=>{const audio=new AudioSystem();audio.ctx={currentTime:80,state:'running'};audio.enabled=true;audio.scene='play';audio.nextBeat=0;const calls=[];audio.tone=(...args)=>calls.push(['tone',args.at(-1)]);audio.hiss=(...args)=>calls.push(['noise',args.at(-1)]);audio.schedule();assert.ok(calls.length>3);assert.ok(calls.every(([,bus])=>bus==='music'));assert.ok(audio.nextBeat>80);assert.ok(audio.beat<3);audio.enabled=false;const n=calls.length;audio.schedule();assert.equal(calls.length,n);});
